### ISSUE TITLE
Is it possible to run dirdiff from command line in Linux

### ISSUE THREAD

**Issue by vortexnix** [will133/vim-dirdiff#10]
This may be a dumb question but I am trying to setup vim-dirdiff as my git difftool. For that, I need to run dirdiff from the command line directly. Also, it would be nice if I can do a vimdiff of directories directly from command line. Thanks.

**Comment by BarrettLowe** [comment]
I use zsh and do something like this in my .zshrc file:
`vimDirDiff()
{
echo "Please wait while vim diffs the directories"
args=$@
vim -f "+execute \"DirDiff $args\"
echo "vimDirDiff Done"
}`

**Comment by 9527KGG** [comment]
vim -c "DirDiff $1 $2"

**Comment by will133** [comment]
That -c command should work.
