### ISSUE TITLE
`!LANG=C diff` doesn't work under Windows cygwin

### ISSUE THREAD

**Issue by ZSaberLv0** [will133/vim-dirdiff#13]
with the default config, `g:DirDiffForceLang` would result these cmd:

```
:!LANG=C diff ...
```

which doesn't work under Windows cygwin, since LANG is not a valid command

workaround:

```
let g:DirDiffLangString = 'sh -c LANG=' . g:DirDiffForceLang . ' '
```

**Comment by hcgraf** [comment]
A similar problem occurs with the `tcsh` shell on unix.
There, the workaround would be:
```
let g:DirDiffLangString = 'env LANG=' . g:DirDiffForceLang . ' '
```
Something more portable is probably needed here…
With a few trials, I couldn't come up with something that works equally well under `bash`, `tcsh` and `cygwin` :(

**Comment by will133** [comment]
I have a recent pull request that seems to fix this.  Since I do not have a Windows box now it's somewhat hard to test.  I'll close this for now.

**Comment by ssoriche** [comment]
I've had this same problem because I run `fish` as my shell. Explicitly setting `let g:DirDiffLangString = 'env LANG=' . g:DirDiffForceLang . ' '` allowed me to use this plugin.
