### ISSUE TITLE
Add installation instructions without pathogen

### ISSUE THREAD

**Issue by gw0** [will133/vim-dirdiff#19]
Vim 8 introduces a packaging system, that makes pathogen and other package managers unnecessary (<https://vi.stackexchange.com/a/12996>). The main difference to them is, that you put the plugin in a different directory.

Please add these installation instructions for "Vim 8+" (works on Debian 9 without any special vim customization):

```
mkdir -p ~/.vim/pack/bundle/start
cd ~/.vim/pack/bundle/start
git clone git://github.com/will133/vim-dirdiff
```

**Comment by MignonBelongie** [comment]
I second this. It worked on out-of-the-box vim on ubuntu 18.04.
(Note that the name 'bundle' could be replaced with any other name, which could be specific to this plugin, or intended for multiple plugins, like 'bundle'.)

**Comment by will133** [comment]
Added to readme.
