### ISSUE TITLE
Feature request: set filetype

### ISSUE THREAD

**Issue by MiguelLatorre** [will133/vim-dirdiff#3]
First, thanks for this great plugin.

I think it would be nice to have a filetype set for the main buffer window (the one with the file names) at the bottom.

Just for reference, I'm currently setting, in my modified dirdiff plugin, the "dirdiff" filetype.

**Comment by will133** [comment]
I'm just curious, what would be the benefit for setting the file type?

**Comment by MiguelLatorre** [comment]
Setting automands, display a custom buffer name, instead of a simple "1" (in plugins like powerline, airline, lightline), ...

I currently have in dirdiff.vim:

    setlocal filetype=dirdiff
    setlocal nomodified
    setlocal nomodifiable
    setlocal buftype=nowrite

**Comment by will133** [comment]
Ok, I've added this with c69159f.
