### ISSUE TITLE
DirDiff 'there is no diff at the current line'

### ISSUE THREAD

**Issue by alan73** [will133/vim-dirdiff#4]
I'm trying to use DirDiff plugin for Vim. I installed the latest version with the help of pathogen.

Then created two directories (dir1 and dir2) in /tmp. In each directory created file test (contents are different).

Then launched vim and typed:

:DirDiff /tmp/dir1 /tmp/dir2

Result:

[A]=/tmp/dir1
[B]=/tmp/dir2
Usage:   <Enter>/'o'=open,'s'=sync,'q'=quit
Options: 'u'=update,'x'=set excludes,'i'=set ignore,'a'=set args
Diff Args: -r --brief

==> Flies [A]/file и [B]/file are different

Footer of window contains:

There is no diff at the current line!

Vim doesn't respond on my requests for viewing file diffs (by means of pressing Enter/o).

What can be the reason?

OS: Ubuntu 14.04 Vim: 7.4.52

**Comment by will133** [comment]
Hmm, do you know if your LANG environment is set to something other than  "C"?
The char between [A]/file and [B]/file seems to be generated by the locale for diff it seems?
Will 

    On Friday, July 8, 2016 10:46 AM, alan73 <notifications@github.com> wrote:
 

 I'm trying to use DirDiff plugin for Vim. I installed the latest version with the help of pathogen.Then created two directories (dir1 and dir2) in /tmp. In each directory created file test (contents are different).Then launched vim and typed::DirDiff /tmp/dir1 /tmp/dir2Result:[A]=/tmp/dir1
[B]=/tmp/dir2
Usage: /'o'=open,'s'=sync,'q'=quit
Options: 'u'=update,'x'=set excludes,'i'=set ignore,'a'=set args
Diff Args: -r --brief==> Flies [A]/file и [B]/file are differentFooter of window contains:There is no diff at the current line!Vim doesn't respond on my requests for viewing file diffs (by means of pressing Enter/o).What can be the reason?OS: Ubuntu 14.04 Vim: 7.4.52—

**Comment by audricschiltknecht** [comment]
I've got the same problem. When setting LANG to "C", works fine.

**Comment by tex** [comment]
Fix for this is in #7

**Comment by ezh** [comment]
This is my working settings for ru_RU.UTF-8.

let g:DirDiffForceLang = "C"
let g:DirDiffTextFiles = "Файлы"
let g:DirDiffTextAnd = " и "
let g:DirDiffTextDiffer = " различаются"

IMHO this information must be in README.MD with bold lines. So users with different locales may create proper configuration.

**Comment by Grueslayer** [comment]
Fix #7 is nice for UN*X like systems but makes plugin not work by default on native Windows systems (Command !LANG=C is not valid for cmd.exe). So we need a usable default for win32 in default setup (let g:DirDiffForceLang = "")

**Comment by will133** [comment]
Yes, I agree we need some sort of default on Windows.  I'm not sure how

**Comment by jdeniau** [comment]
Continuing this issue because I'm having it too : 
I'm on a french server and even if I run `LANG=C diff a b`, the output is in french.

I forced the `let g:DirDiffForceLang = "en_US"` and DirDiff now works
