### ISSUE TITLE
improvement: marker for finished files

### ISSUE THREAD

**Issue by ykmantri** [will133/vim-dirdiff#6]
1. It would be really nice to add marker some graphical or texual representation for completed files in diff.
2. It would be nice to hide the file if that file is not expected to diffed
3. exporting the current fileset which are resolved / which are still different after merging / unchanged / same / etc would be a good idea.

regards,
Yogesh Mantri
ykmantri@gmail.com

**Comment by will133** [comment]
1. If you hit "s" and do "a" or "b" the entry would actually disappear from the list.  You can also hit "u" to update the list (after running diff again)
2. I'm not sure what you meant.  Doing a "u" may help you filter down this.
3. Do you have a big change set so running the diff would be very expense?
