### ISSUE TITLE
it would be nice to have more stable window layout

### ISSUE THREAD

**Issue by tex** [will133/vim-dirdiff#8]
when you hit enter on some file and then on different file, all buffers are closed and then re-created. this causes heavy flickering.

**Comment by will133** [comment]
Yeah, this is pretty annoying to me too.  I'm doing essentially a vim diffsplit.  I'm not sure how I can replace the buffers without closing them first though.  If you know of a better way to do this, I'd be happy to investigate.

**Comment by tex** [comment]
This https://github.com/dkprice/vim-dirdiff/commit/5d0181b38ab55217814a79bb6ee6e7dd16611feb does seem to work. I had a problem with it though when using neovim - it freezes neovim after a few diffs...

**Comment by junkblocker** [comment]
FYI, `drop` use in that fix has problem with symlinked filenames while the current implementation does not have that issue. `drop` will take you to the same buffer for a symlink or original causing complete breakage of dirdiff logic there.

**Comment by will133** [comment]
I've not touched this for a while, but if anybody is interested in submitting a pull request with the latest master with this change I can take a look again.

**Comment by tex** [comment]
@will133 done, here you are
